Maintenance = [
    {"sop_id": "SOP007", "interlock_name": "ESD Push button_Under Maintenance", "alert_category": "Safety", "equipment_name": "ESD"},
    {"sop_id": "SOP008", "interlock_name": "Rim Seal system_Under Maintenance", "alert_category": "Safety", "equipment_name": "RimSeal"},
    {"sop_id": "SOP009", "interlock_name": "Tank_Under Maintenance", "alert_category": "Safety", "equipment_name": ""},
    {"sop_id": "SOP010", "interlock_name": "ROSOV_Under Maintenance", "alert_category": "Safety", "equipment_name": "ROSOV STATUS"},
    {"sop_id": "SOP010A", "interlock_name": "MOV_Under Maintenance", "alert_category": "Safety", "equipment_name": "MOV STATUS"},
    {"sop_id": "SOP011", "interlock_name": "VFT_Under Maintenance", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP012", "interlock_name": "Secondary Radar_Under Maintenance", "alert_category": "Safety", "equipment_name": "Secondary Radar"},
    {"sop_id": "SOP013", "interlock_name": "Fire engine_Under Maintenance", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP013", "interlock_name": "JockeyPump_Under Maintenance", "alert_category": "Safety", "equipment_name": "Jockey Pump"},
    {"sop_id": "SOP013", "interlock_name": "HydrantPT_Under Maintenance", "alert_category": "Safety", "equipment_name": "PT Hydrant"},
    {"sop_id": "SOP014", "interlock_name": "HCD_Under Maintenance", "alert_category": "Safety", "equipment_name": "HCD"}
]

Fault = [
    {"sop_id": "SOP004", "interlock_name": "Rim Seal system_Fault activated", "alert_category": "Safety", "equipment_name": "RimSeal"},
    {"sop_id": "SOP016", "interlock_name": "HCD_Fault activated", "alert_category": "Safety", "equipment_name": "HCD"},
    {"sop_id": "SOP017", "interlock_name": "AirCompressor_Fault activated", "alert_category": "Safety", "equipment_name": "Air Compressor"},
    {"sop_id": "SOP018", "interlock_name": "ROSOV_FailtoClose", "alert_category": "Safety", "equipment_name": "ROSOV STATUS"},
    {"sop_id": "SOP019", "interlock_name": "Fire engine_ FailtoStart", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "Fireengine_LLOP", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "FireEngine_HWOT", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP019", "interlock_name": "FireEngine_Tripped", "alert_category": "Safety", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP020", "interlock_name": "Jockeypump_ FailtoStart", "alert_category": "Safety", "equipment_name": "Jockey Pump"}
]

Normal = [
    {"sop_id": "SOP001", "interlock_name": "HHH alarm from VFT", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP001", "interlock_name": "HHH alarm from Secondary Radar guage", "alert_category": "Safety", "equipment_name": "Secondary Radar"},
    {"sop_id": "SOP01A", "interlock_name": "ROSOV_Close Status", "alert_category": "Safety", "equipment_name": "ROSOV STATUS"},
    {"sop_id": "SOP01A", "interlock_name": "MOV_Close Status", "alert_category": "Safety", "equipment_name": "MOV STATUS"},
    {"sop_id": "SOP002", "interlock_name": "Plant ESD activated", "alert_category": "Safety", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "All ROSOVs closed", "alert_category": "Safety", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "Tanks in TTL Dispatch in Dormant Mode", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "As Power ESD Activation in Main PMCC Panel after 120 Sec", "alert_category": "Safety", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "Hooter cum strobe for ESD activated in control room", "alert_category": "Safety", "equipment_name": "Hooter"},
    {"sop_id": "SOP02A", "interlock_name": "Siren Activated", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "ESD Command To Process PLC", "alert_category": "Safety", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "All DBBVs Closed", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "All Tanks in Dormant Mode", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "All TLF Product Pumps Stopped", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "TLF Gantry Permissive Power Off", "alert_category": "Process", "equipment_name": "ESD"},
    {"sop_id": "SOP02A", "interlock_name": "Barrier Gate opened", "alert_category": "Process", "equipment_name": "Barrier Gate"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_VFT_Failed", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_Secondary Radar Guage_Failed", "alert_category": "Safety", "equipment_name": "Secondary Radar"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_VFT_Sucess", "alert_category": "Safety", "equipment_name": "VFT"},
    {"sop_id": "SOP003", "interlock_name": "Proof Test_Secondary Radar Guage_Sucess", "alert_category": "Safety", "equipment_name": "Secondary Radar"},
    {"sop_id": "SOP005", "interlock_name": "HCD_20% LEL activated", "alert_category": "Safety", "equipment_name": "HCD"},
    {"sop_id": "SOP005", "interlock_name": "HCD_40% LEL activated", "alert_category": "Safety", "equipment_name": "HCD"},
    {"sop_id": "SOP006", "interlock_name": "Earthing Failure Alarm", "alert_category": "Process", "equipment_name": "Loading Point"},
    {"sop_id": "SOP015", "interlock_name": "Dykevalve_Activated", "alert_category": "Safety", "equipment_name": "Dyke"},
    {"sop_id": "SOP021", "interlock_name": "SafetyPLC_Communication fail", "alert_category": "Process", "equipment_name": "PLC A is Master"},
    {"sop_id": "SOP021", "interlock_name": "UPS_Fail", "alert_category": "Process", "equipment_name": "UPS"},
    {"sop_id": "SOP021", "interlock_name": "UPS_Lowbattery", "alert_category": "Process", "equipment_name": "UPS"},
    {"sop_id": "SOP021", "interlock_name": "ProcessPLC_Communication fail", "alert_category": "Process", "equipment_name": "PLC B is Master"},
    {"sop_id": "SOP022", "interlock_name": "LRC Master Switchover required in 30 days", "alert_category": "Process", "equipment_name": "LRC Switchover"},
    {"sop_id": "SOP023", "interlock_name": "Firefighting system parameter", "alert_category": "Safety", "equipment_name": "Fire Pump"},
    {"sop_id": "SOP023", "interlock_name": "All TLF Product Pumps Stopped", "alert_category": "Process", "equipment_name": "Fire Engine"},
    {"sop_id": "SOP023", "interlock_name": "TLF Header Line MOV Close", "alert_category": "Process", "equipment_name": "Fire Pump"},
    {"sop_id": "SOP023", "interlock_name": "Gantry Permissive Off", "alert_category": "Process", "equipment_name": "Fire Pump"},
    {"sop_id": "SOP023", "interlock_name": "All BCU Permissive Fail Status", "alert_category": "Gantry", "equipment_name": "Fire Pump"},
    {"sop_id": "SOP024", "interlock_name": "Day End totaliser Mismatch", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP025", "interlock_name": "BCU Local loading", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP025", "interlock_name": "BCU permissive fail status", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP026", "interlock_name": "BCU vs MFM totalizer mismatch alarm", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP027", "interlock_name": "K Factor Change_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP027", "interlock_name": "K Factor Change_MFM", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "No Flow alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Low Flow alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "High Flow Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Unauthorized Flow Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Meter overrun Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Blend overdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Blend Underdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Additive Overdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "Additive Underdose Alarm_BCU", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP028", "interlock_name": "BCU Loading Status", "alert_category": "Gantry", "equipment_name": "Loading Point"},
    {"sop_id": "SOP029", "interlock_name": "Tank leakage alarm", "alert_category": "Process", "equipment_name": ""},
    {"sop_id": "SOP030", "interlock_name": "Manual - bay assignment of more 5% of total TT loaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP030", "interlock_name": "Manual FAN printed more 5% of total TT loaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP031", "interlock_name": "Min 5% Manual Cross-check records", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP032", "interlock_name": "Primary Radar Guage_H alarm", "alert_category": "Process", "equipment_name": "Primary Radar"},
    {"sop_id": "SOP032", "interlock_name": "Primary Radar Guage_HH alarm", "alert_category": "Process", "equipment_name": "Primary Radar"},
    {"sop_id": "SOP033", "interlock_name": "SickTT Reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP034", "interlock_name": "Cancel TT Reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP035", "interlock_name": "Gantry Permissive_Override", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP036", "interlock_name": "Unauthorized flow_BCU", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP037", "interlock_name": "Manual Bay reasignment reported", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP038", "interlock_name": "TT Overloaded", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP039", "interlock_name": "Day End Report", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP040", "interlock_name": "TAS User access report", "alert_category": "Gantry", "equipment_name": "BCU"},
    {"sop_id": "SOP041", "interlock_name": "Local order/Standalone Order Entryt", "alert_category": "Gantry", "equipment_name": "BCU"},
]