system_classification = {
            "VFT": "Safety",
            "UPS": "Process",
            "ROSOV": "Safety", 
            "RIMSEAL": "Safety",
            "RADAR": "Safety",
            "PUMP": "Process",
            "PT": "Safety",
            "PRIMARY LEVEL": "Process",
            "PLC": "Process",
            "MOV": "Safety",
            "MFM": "Gantry",
            "LRC SWITCHOVER": "Process",
            "JOCKEY PUMP": "Safety",
            "HOOTER": "Safety",
            "HCD": "Safety",
            "GANTRY OVERRIDE": "Safety",
            "GANTRY BCU": "Gantry",
            "FIRE ENGINE": "Safety",
            "FIRE EFFECT": "Process",
            "ESD EFFECT": "Process",
            "ESD": "Safety",
            "DYKE": "Safety",
            "BARRIER GATE": "Process"
}