role_Mapping = {
    "VTS":{
        "VTS RouteDeviation FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P90D"},
        "Unauthorized Stoppage FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P90D"},
        "VTS PowerDisconnect FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P730D"},
        "VTS Device Tampering FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P730D"},
        "VTS Offline FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P90D"},
        "Night Driving FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P7D"},
        "Speed Violation FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P7D"},
        "NoHalt Zone FirstTime":{"rolemailto":{"0": "Safety ofiicer","1": "Location In-charge","2": "Safety ofiicer,Location In-charge"},
                                        "mqof":{"0": "Safety ofiicer","1": "Location In-charge"},"block_time":"P90D"},

        "VTS RouteDeviation SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        "Unauthorized Stoppage SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        "VTS PowerDisconnect SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        "VTS Device Tampering SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        "VTS Offline SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        "Night Driving SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P90D"},
        "Speed Violation SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P90D"},
        "NoHalt Zone SecondTime":{"rolemailto":{"0": "Location In-charge","1": "Zonal HSSE","2": "Location In-charge,Zonal HSSE"},
                                        "mqof":{"0": "Location In-charge","1": "Zonal HSSE"},"block_time":"P730D"},
        
        "VTS RouteDeviation ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "Unauthorized Stoppage ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "VTS PowerDisconnect ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "VTS Device Tampering ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "VTS Offline ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "Night Driving ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "Speed Violation ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        "NoHalt Zone ThirdTime":{"rolemailto":{"0": "Zonal HSSE","1": "Zonal Operations Head","2": "Zonal HSSE,Zonal Operations Head"},
                                        "mqof":{"0": "Zonal HSSE","1": "Zonal Operations Head"},"block_time":"P730D"},
        
        "VTS RouteDeviation FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "Unauthorized Stoppage FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "VTS PowerDisconnect FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "VTS Device Tampering FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "VTS Offline FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "Night Driving FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "Speed Violation FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},
        "NoHalt Zone FourthTime":{"rolemailto":{"0": "Zonal Operations Head","1": "HQO HSSE Team","2": "Zonal Operations Head,HQO HSSE Team"},
                                        "mqof":{"0": "Zonal Operations Head","1": "HQO HSSE Team"},"block_time":"P730D"},

        "VTS RouteDeviation FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Unauthorized Stoppage FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS PowerDisconnect FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS Device Tampering FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS Offline FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Night Driving FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Speed Violation FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "NoHalt Zone FifthTime":{"rolemailto":{"0": "HQO HSSE Team","1": "HQO Operations Team","2": "HQO HSSE Team,HQO Operations Team"},
                                        "mqof":{"0": "HQO HSSE Team","1": "HQO Operations Team"},"block_time":"P730D"},

        "VTS RouteDeviation SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Unauthorized Stoppage SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS PowerDisconnect SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS Device Tampering SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "VTS Offline SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Night Driving SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "Speed Violation SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"},
        "NoHalt Zone SixthTime":{"rolemailto":{"0": "HQO Operations Team","1": "HQO Operations Team","2": "HQO Operations Team"},
                                        "mqof":{"0": "HQO Operations Team","1": "HQO Operations Team"},"block_time":"P730D"}
}
}

