zone_map = {
    "WZL": "WZ",
    "NWL": "NWZ",
    "EZL": "EZ",
    "NZL": "NZ",
    "NCL": "NCZ",
    "SZL": "SZ",
    "SCL": "SC",
    "SZ": "SZ",
    "EZ": "EZ",
    "SCZ": "SCZ",
    "NWZ": "NWZ",
    "NZ": "NZ",
    "NCZ": "NCZ",
    "WZ": "WZ",
    "NFZ": "NZ",
    "NWF": "NW",
    "NCR": "NCZ",
    "SCR": "SCZ",
    "NWR": "NWZ",
    "SC": "SCZ",
    "NW": "NWZ",
    "COR": "COR"
}
lpg_query = f""" SELECT ZE.EMPLOYEE_NUMBER as EMPLOYEE_NUMBER, ZE.EMPLOYEE_NAME as EMPLOYEE_NAME,  ZE.EMP_EMAIL as EMP_EMAIL, 
                    ZE.EMP_BU_CODE,ZE.PLANT_CODE,ZE.PLANT_DESC, ZR.ROLE_NAME as ROLE_NAME, ZR.LOCATION as LOCATION, EPL.ZZONE as zone
                FROM ZGRCCV_ROLE_STG ZR LEFT JOIN ZHRCV_EMP_NONHCM_STG ZE on ZR.USER_NAME = ZE.EMPLOYEE_NUMBER 
                    LEFT JOIN ZMMCV_PLANT_STG EPL on ZR.LOCATION = EPL.PLANT
                WHERE ZR.LOCATION like '2%' and ZR.ROLE_NAME IN 
                ('PM_MAINT_OFFICER', 'SD_LSBU_HEAD','IL_CHMNGR_LPGHSEZONE','IL_CHMNGR_LPGONDZONE','IL_OPNHEAD_LPGZONE',
                'SD_LZONAL_HEAD','SD_LZONAL_OFFICER','SD_RREGNL_MNGR','IL_LPGPLNT_INCHARG','IL_LPG_PLNGOFCR','PM_SAFETY_OFFICER'); """

sod_query = f""" SELECT ZE.EMPLOYEE_NUMBER as EMPLOYEE_NUMBER, ZE.EMPLOYEE_NAME as EMPLOYEE_NAME,  ZE.EMP_EMAIL as EMP_EMAIL, 
                    ZE.EMP_BU_CODE,ZE.PLANT_CODE,ZE.PLANT_DESC, ZR.ROLE_NAME as ROLE_NAME, ZR.LOCATION as LOCATION, EPL.ZZONE as zone
                FROM ZGRCCV_ROLE_STG ZR LEFT JOIN ZHRCV_EMP_NONHCM_STG ZE on ZR.USER_NAME = ZE.EMPLOYEE_NUMBER 
                    LEFT JOIN EDW_DC_PLANT EPL on ZR.LOCATION = EPL.PLANT
                WHERE ZR.LOCATION like '1%' and ZR.ROLE_NAME IN 
                ("IL_MNGR_DNTSODZONE","IL_PLANING_OFFCER","IL_CHMNGR_DNTSODZONE"," IL_GM_SOD","IL_DGM_SODNFP",
                "IL_EXEOFF_DNTSODZONE","IL_SRMNGR_SODNFP","IL_ED_SOD", "IL_OPNHEAD_SODZONE") """